sudo: required
services:
  - docker

before_script:
  - docker-compose -f docker-compose.test.yml up --build -d

script:
  - curl http://127.0.0.1:8005/
  - if [[ ! -f "index.html" ]]; then exit 1; fi

after_script:
  - docker-compose -f docker-compose.test.yml down

notifications:
  email: docker@katagena.com
