sut:
  build: .
  ports:
    - "8005:80"
  environment:
    - OUTPUT_TEMPLATE=kendall
    - PHONE=+33602030405
    - EMAIL=docker@katagena.com
    - ADDRESS=25 Rue Delphin Loche
    - RESUME_JSON_URL=https://raw.githubusercontent.com/nouchka/docker-hackmyresume/master/resume.json
