version: '2'

services:
  hackmyresume:
    build: .
    image: nouchka/hackmyresume-web
    environment:
      - OUTPUT_TEMPLATE=kendall
      - TEMPLATE_GIT=https://github.com/nouchka/jsonresume-theme-kendall.git
      - PHONE=+33602030405
      - EMAIL=docker@katagena.com
      - ADDRESS=25 Rue Delphin Loche
      - RESUME_JSON_URL=https://raw.githubusercontent.com/nouchka/japromis.katagena.com/master/resume.json
    ports:
      - "8005:80"
